# NOTE IPTC: Describes standardized textual metadata used by news agencies and editors.
# Focus on fields from the Envelope, Application, and NewsPhoto records for describing content, authorship, rights, and editorial context.

IPTC_TAGS = {
    # Envelope Record (Record 1)
    "EnvelopeRecordVersion": {"record": 1, "tag": 0, "type": "SHORT", "count": 1},
    "Destination": {"record": 1, "tag": 5, "type": "ASCII", "count": "Any"},
    "FileFormat": {"record": 1, "tag": 20, "type": "SHORT", "count": 1},
    "FileVersion": {"record": 1, "tag": 22, "type": "SHORT", "count": 1},
    "ServiceIdentifier": {"record": 1, "tag": 30, "type": "ASCII", "count": "Any"},
    "EnvelopeNumber": {"record": 1, "tag": 40, "type": "ASCII", "count": 8},
    "ProductID": {"record": 1, "tag": 50, "type": "ASCII", "count": "Any"},
    "EnvelopePriority": {"record": 1, "tag": 60, "type": "ASCII", "count": 1},
    "DateSent": {"record": 1, "tag": 70, "type": "ASCII", "count": 8},
    "TimeSent": {"record": 1, "tag": 80, "type": "ASCII", "count": 11},
    "CodedCharacterSet": {"record": 1, "tag": 90, "type": "UTF_8", "count": "Any"},
    "UniqueObjectName": {"record": 1, "tag": 100, "type": "ASCII", "count": "Any"},
    "ARMIdentifier": {"record": 1, "tag": 120, "type": "SHORT", "count": 1},
    "ARMVersion": {"record": 1, "tag": 122, "type": "SHORT", "count": 1},

    # Application Record (Record 2)
    "ApplicationRecordVersion": {"record": 2, "tag": 0, "type": "SHORT", "count": 1},
    "ObjectTypeReference": {"record": 2, "tag": 3, "type": "ASCII", "count": "Any"},
    "ObjectAttributeReference": {"record": 2, "tag": 4, "type": "ASCII", "count": "Any"},
    "ObjectName": {"record": 2, "tag": 5, "type": "ASCII", "count": "Any"},
    "EditStatus": {"record": 2, "tag": 7, "type": "ASCII", "count": "Any"},
    "EditorialUpdate": {"record": 2, "tag": 8, "type": "ASCII", "count": 2},
    "Urgency": {"record": 2, "tag": 10, "type": "ASCII", "count": 1},
    "SubjectReference": {"record": 2, "tag": 12, "type": "ASCII", "count": "Any"},
    "Category": {"record": 2, "tag": 15, "type": "ASCII", "count": "Any"},
    "SupplementalCategories": {"record": 2, "tag": 20, "type": "ASCII", "count": "Any"},
    "FixtureIdentifier": {"record": 2, "tag": 22, "type": "ASCII", "count": "Any"},
    "Keywords": {"record": 2, "tag": 25, "type": "ASCII", "count": "Any"},
    "ContentLocationCode": {"record": 2, "tag": 26, "type": "ASCII", "count": "Any"},
    "ContentLocationName": {"record": 2, "tag": 27, "type": "ASCII", "count": "Any"},
    "ReleaseDate": {"record": 2, "tag": 30, "type": "ASCII", "count": 8},
    "ReleaseTime": {"record": 2, "tag": 35, "type": "ASCII", "count": 11},
    "ExpirationDate": {"record": 2, "tag": 37, "type": "ASCII", "count": 8},
    "ExpirationTime": {"record": 2, "tag": 38, "type": "ASCII", "count": 11},
    "SpecialInstructions": {"record": 2, "tag": 40, "type": "ASCII", "count": "Any"},
    "ActionAdvised": {"record": 2, "tag": 42, "type": "ASCII", "count": 2},
    "ReferenceService": {"record": 2, "tag": 45, "type": "ASCII", "count": "Any"},
    "ReferenceDate": {"record": 2, "tag": 47, "type": "ASCII", "count": "Any"},
    "ReferenceNumber": {"record": 2, "tag": 50, "type": "ASCII", "count": "Any"},
    "DateCreated": {"record": 2, "tag": 55, "type": "ASCII", "count": 8},
    "TimeCreated": {"record": 2, "tag": 60, "type": "ASCII", "count": 11},
    "DigitalCreationDate": {"record": 2, "tag": 62, "type": "ASCII", "count": 8},
    "DigitalCreationTime": {"record": 2, "tag": 63, "type": "ASCII", "count": 11},
    "OriginatingProgram": {"record": 2, "tag": 65, "type": "ASCII", "count": "Any"},
    "ProgramVersion": {"record": 2, "tag": 70, "type": "ASCII", "count": "Any"},
    "ObjectCycle": {"record": 2, "tag": 75, "type": "ASCII", "count": 1},
    "By-line": {"record": 2, "tag": 80, "type": "ASCII", "count": "Any"},
    "By-lineTitle": {"record": 2, "tag": 85, "type": "ASCII", "count": "Any"},
    "City": {"record": 2, "tag": 90, "type": "ASCII", "count": "Any"},
    "Sub-location": {"record": 2, "tag": 92, "type": "ASCII", "count": "Any"},
    "Province-State": {"record": 2, "tag": 95, "type": "ASCII", "count": "Any"},
    "Country-PrimaryLocationCode": {"record": 2, "tag": 100, "type": "ASCII", "count": 3},
    "Country-PrimaryLocationName": {"record": 2, "tag": 101, "type": "ASCII", "count": "Any"},
    "OriginalTransmissionReference": {"record": 2, "tag": 103, "type": "ASCII", "count": "Any"},
    "Headline": {"record": 2, "tag": 105, "type": "ASCII", "count": "Any"},
    "Credit": {"record": 2, "tag": 110, "type": "ASCII", "count": "Any"},
    "Source": {"record": 2, "tag": 115, "type": "ASCII", "count": "Any"},
    "CopyrightNotice": {"record": 2, "tag": 116, "type": "ASCII", "count": "Any"},
    "Contact": {"record": 2, "tag": 118, "type": "ASCII", "count": "Any"},
    "Caption-Abstract": {"record": 2, "tag": 120, "type": "ASCII", "count": "Any"},
    "LocalCaption": {"record": 2, "tag": 121, "type": "ASCII", "count": "Any"},
    "Writer-Editor": {"record": 2, "tag": 122, "type": "ASCII", "count": "Any"},
    "RasterizedCaption": {"record": 2, "tag": 125, "type": "UNDEFINED", "count": "Any"},
    "ImageType": {"record": 2, "tag": 130, "type": "ASCII", "count": 2},
    "ImageOrientation": {"record": 2, "tag": 131, "type": "ASCII", "count": 1},
    "LanguageIdentifier": {"record": 2, "tag": 135, "type": "ASCII", "count": "Any"},
}

# Reverse lookup dictionary with (record, tag) as key
IPTC_TAGS_DICT_REV = {(v["record"], v["tag"]): k for k, v in IPTC_TAGS.items()}

